export = Object.freeze({
    SIGNUP: "SIGNUP",
    MOVE_PIECES: "MOVE_PIECES",
    UPDATE_PIECES: "UPDATE_PIECES",
    WINNER:"WINNER",
    START: "START",
    ERROR: "ERROR",
    GAME_STARTED: "GAME_STARTED",
    USER_TURN_STARTED: "USER_TURN_STARTED",
    START_ROOM_EVENT: "START_ROOM_EVENT",
    SIGNUP_SOCKET_EVENT: "SIGNUP_SOCKET_EVENT",
    SIGNUP_TABLE_SOCKET: "SIGNUP_TABLE_SOCKET",
    EMIT_ERROR: "EMIT_ERROR",
    EMIT_MOVE_PIECES: "EMIT_MOVE_PIECES",
    EMIT_UPDATE_PIECES: "EMIT_UPDATE_PIECES",
    EMIT_ROUND_TIMER: "EMIT_ROUND_TIMER",
    JOIN:"JOIN",
    REJOIN:"REJOIN"
    })
  